import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navLinks = [
  {
    name: "Register",
    href: "/register",
  },
  { name: "Login", href: "/login" },
  { name: "Forgot Passwrod", href: "/forgot-password" },
];

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {navLinks.map((link) => {
          return (
            <Link href={link.href} key={link.name}>
              {link.name}++++++
            </Link>
          );
        })}
        <h1>Hello World</h1>
        {children}
      </body>
    </html>
  );
}
