export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <header style={{ background: "green" }}>
        <h1> Header</h1>
      </header>

      <body>{children}</body>
      <footer style={{ background: "red" }}>
        <h1> footer</h1>
      </footer>
    </html>
  );
}
