import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next js Tutorial", // fallback
    template: "%s What Ever", // prefix Child Routes i.e the %s will be replaced by the title from the child routes, multi page pattern
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1> Header</h1>
        </header>
        {children}
        <footer>
          <h1> footer</h1>
        </footer>
      </body>
    </html>
  );
}
