"use client";
// import type { Metadata } from "next";
import Link from "next/link";
import { usePathname } from "next/navigation";
import "../../../globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const navLinks = [
  {
    name: "Register",
    href: "/register",
  },
  { name: "Login", href: "/login" },
  { name: "Forgot Passwrod", href: "/forgot-password" },
];

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathName = usePathname();
  console.log(pathName);
  return (
    <html lang="en">
      <body>
        {navLinks.map((link) => {
          const isActive =
            pathName.startsWith(link.href.toLowerCase()) && link.href !== "/";
          return (
            <Link
              href={link.href}
              key={link.name}
              className={isActive ? "font-bold mr-4  text-2xl" : "mr-4"}
            >
              {link.name}
            </Link>
          );
        })}
        {children}
      </body>
    </html>
  );
}
