"use client";
// import type { Metadata } from "next";
import Link from "next/link";
import { usePathname } from "next/navigation";
import "../../../globals.css";
import { useState } from "react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const navLinks = [
  {
    name: "Register",
    href: "/register",
  },
  { name: "Login", href: "/login" },
  { name: "Forgot Passwrod", href: "/forgot-password" },
];

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathName = usePathname();
  const [input, setInput] = useState("");
  console.log(pathName);
  return (
    <div>
      <div>
        <input value={input} onChange={(e) => setInput(e.target.value)} />
      </div>
      {navLinks.map((link) => {
        const isActive =
          pathName.startsWith(link.href.toLowerCase()) && link.href !== "/";
        return (
          <Link
            href={link.href}
            key={link.name}
            className={isActive ? "font-bold mr-4  text-2xl" : "mr-4"}
          >
            {link.name}
          </Link>
        );
      })}
      {children}
    </div>
  );
}
