import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue" }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "green" }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
